laekov/fastmoe

- .pylintrc
- fmoe/Megatron.LICENSE
- fmoe/megatron.py
- fmoe/transformer.py
load/save fp16/fp32 checkpoints.
> Checkpoint

- cuda/moe.cpp
- fmoe/balance.py
- fmoe/gates.py
- fmoe/layers.py
- fmoe/megatron.py
- fmoe/transformer.py
- tests/benchmark_mlp.py
- tests/test_numerical.py
- Add gate hook
- Add GShard's auxiliary loss
- Add noisy gate balance strategy
> Add balance strategy

- tests/test_numerical.py
- tests/test_zero.py
The `test_numerical.py` becomes broken for some private import. (which is a mass)
> fix tests after updating megatron

- .gitignore
- fmoe/layers.py
- fmoe/transformer.py
- tests/moe.py
- tests/test_numerical.py
- tests/test_zero.py
- mask some tensors of tokens for fmoe forward
- pass a list of expert classes to specify what experts in what order want to use
> mask and experts list

- cuda/parallel_linear.cuh
> Fixed asynchronous streams in column reduce kernel call

- fmoe/distributed.py
- fmoe/functions.py
- fmoe/layers.py
- fmoe/megatron/balance.py
- fmoe/megatron/distributed.py
- fmoe/megatron/layers.py
- fmoe/transformer.py
> Use moe_group instead of world for MoE

- fmoe/megatron/balance.py
https://github.com/laekov/fastmoe/issues/63
> fix fp16 training with balance loss

- examples/transformer-xl/utils/proj_adaptive_softmax.py
This PR is trying to fix the transformer examples. The current version could not run with `run_wt103_base.sh`.
Thank you for your time on reviewing this PR :)
> Fix transformer-XL examples

- fmoe/gates/gshard_gate.py
Not always set `self.random_routing = True`
> Fix GShardGate random_routing

- fmoe/gates/faster_gate.py
- tests/test_ddp.py
- tests/test_faster_gate.py
Add the topology-aware gate in PPoPP'22 paper _FasterMoE: Modeling and Optimizing Training of Large-Scale Dynamic Pre-Trained Models_. 
The code is copied from <https://github.com/thu-pacman/FasterMoE>. Documents and licenses will be added later when the whole project is integrated into FastMoE.
> Faster topo gate

- fmoe/fastermoe/schedule.py
> Fix smart schedule with older PyTorch

- tests/test_gates.py
> Fix gshard gate test

- fmoe/distributed.py
As seen in #116, I noticed that there was not any document that mentions the initialization issue.
> Add a hint for DGDP synchronization

- fmoe/distributed.py
- fmoe/utils.py
- tests/test_numerical.py
> Fix Broadcast rank bug in DGDP

- cuda/global_exchange.cpp
> Fix nccl uid bcast for torch v1.12.0

- fmoe/gates/gshard_gate.py
As mentioned in https://github.com/laekov/fastmoe/issues/129
> Fix GshardGate top1_idx

- cuda/fastermoe/smart_schedule.cpp
- cuda/fastermoe/smart_schedule.h
- cuda/fmoe_cuda.cpp
- cuda/global_exchange.cpp
> Compatibility to older cuda and torch 1.13

- fmoe/distributed.py
As mentioned in https://github.com/laekov/fastmoe/issues/143
> remove synchronize

- cuda/fastermoe/smart_schedule.h
- examples/megatron/v2.5.patch
- fmoe/distributed.py
- fmoe/gates/naive_gate.py
- fmoe/megatron/distributed.py
- fmoe/megatron/layers.py
- fmoe/megatron/patch.py
- setup.py
Adapt the API for Megatron v2.5
Fix the calculation of MoE gate loss when using pipeline parallelism
Fix some minor bugs.
> FastMoE with Megatron-LM v2.5

- cuda/fastermoe/smart_schedule.cpp
- cuda/fastermoe/smart_schedule.h
- fmoe/fastermoe/expert_utils.py
- fmoe/fastermoe/schedule.py
- fmoe/layers.py
- fmoe/megatron/layers.py
- fmoe/transformer.py
support n_expert > 1
fix minor bugs in expert shadowing
> make FasterMoE more general

- fmoe/linear.py
> Revert "convert input to same type as weight for mixed precision training"

- fmoe/linear.py
> Cast input to weights type for AMP support

- README.md
added link to _installation-guide.md_
> Added link to installation guide

- cuda/fmoe_cuda.cpp
- cuda/global_exchange.cpp
- setup.py
- tests/test_comm.py
> Fix ProcessGroupNCCL mismatch in pytorch2

- doc/fastermoe/README.md
As mentioned in https://github.com/laekov/fastmoe/issues/166
> Update outdated README

- examples/megatron/clip-grad-v2.2.patch
If fmoefy is False, clip_grad_norm_fp32 will crash.
> update clip-grad-v2.2.patch for grads_in_moe is empty
